### ISSUE TITLE
SS Standardというフォントを使った場合に画像が切れる問題

### ISSUE THREAD

**Issue by yoneapp** [kishikawakatsumi/SymbolFontKit#1]
こんにちは、SymbolFontKit を使ってみました。
http://symbolset.com のSS Standardで使ってみたところ
文字の上の少しが欠けてしまいました。

いくつか表示する文字を変えてみましたが駄目でした。
一応、ご報告させて頂きます。

参考画像：
https://www.dropbox.com/s/ks901xakdzmyk8f/IMG_2283.PNG

**Comment by kishikawakatsumi** [comment]
報告ありがとうございます。
SymbolSetは僕も持ってるので調べますね。

**Comment by kishikawakatsumi** [comment]
完全に自動でうまくいくようにはできてないですが、あまり変にならないようにしました。
defaultFont: に与えるサイズをフォントによって調整してください。

**Comment by yoneapp** [comment]
ありがとうございました！
